export const LOADING_HANDLER = 'LOADING_HANDLER';
export const DATA_HANDLER = 'DATA_HANDLER';
export const SELECTED_URL_HANDLER = 'SELECTED_URL_HANDLER';
export const SELECTED_ID_HANDLER = 'SELECTED_ID_HANDLER';
